<FloatLayout>:
    Button:
        text: "Front"
        size_hint: None, None
        size: "200dp", "50dp"
        pos_hint: {"center_x": 0.5, "center_y": 0.8}
    
    TextInput:
        hint_text: "Enter Here"
        size_hint: None, None
        size: "300dp", "40dp"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
    
    TextInput:
        hint_text: "Back"
        size_hint: None, None
        size: "300dp", "40dp"
        pos_hint: {"center_x": 0.5, "center_y": 0.3}
